name: Deploy to AWS

on:
  push:
    branches: [ main ]

permissions:
  id-token: write  # OIDCトークンの取得に必要
  contents: read   # リポジトリのコードを読み取るために必要
  actions: read    # GitHub Actionsの実行コンテキストへのアクセスに必要

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug OIDC claims
        id: get_id_token
        uses: actions/checkout@v4

      - name: Get ID Token
        id: idtoken
        run: |
          # GitHub Actionsの組み込み関数を使用してIDトークンを取得
          TOKEN=$(curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r '.value')
          if [ -z "$TOKEN" ]; then
            echo "Failed to get ID token"
            exit 1
          fi

          # トークンのペイロード部分をデコード
          PAYLOAD=$(echo $TOKEN | cut -d. -f2 | base64 -d 2>/dev/null || echo $TOKEN | cut -d. -f2 | base64 -di 2>/dev/null)
          echo "OIDC Token payload:"
          echo $PAYLOAD | jq .

          # subクレームを抽出
          SUB_CLAIM=$(echo $PAYLOAD | jq -r .sub)
          echo "Sub claim: $SUB_CLAIM"
          echo "sub_claim=$SUB_CLAIM" >> $GITHUB_OUTPUT
        env:
          ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ env.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}
          ACTIONS_ID_TOKEN_REQUEST_URL: ${{ env.ACTIONS_ID_TOKEN_REQUEST_URL }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
          aws-region: ${{ secrets.AWS_REGION }}
          audience: sts.amazonaws.com


      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: shiritoruby
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # ビルドとプッシュ
          docker buildx build \
            --platform linux/amd64 \
            --tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            --tag $ECR_REGISTRY/$ECR_REPOSITORY:latest \
            --push \
            .
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Download task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition shiritoruby \
            --query taskDefinition > task-definition.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1.1.0
        with:
          task-definition: task-definition.json
          container-name: shiritoruby
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1.4.0
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: shiritoruby-service
          cluster: shiritoruby-cluster
          wait-for-service-stability: true

      - name: Run database migrations
        run: |
          aws ecs run-task \
            --cluster shiritoruby-cluster \
            --task-definition shiritoruby \
            --launch-type FARGATE \
            --network-configuration "awsvpcConfiguration={subnets=[ $(aws ecs describe-services --cluster shiritoruby-cluster --services shiritoruby-service --query 'services[0].networkConfiguration.awsvpcConfiguration.subnets[0]' --output text) ],securityGroups=[ $(aws ecs describe-services --cluster shiritoruby-cluster --services shiritoruby-service --query 'services[0].networkConfiguration.awsvpcConfiguration.securityGroups[0]' --output text) ],assignPublicIp=ENABLED}" \
            --overrides '{"containerOverrides": [ {"name": "shiritoruby", "command": [ "./bin/rails", "db:migrate" ]} ]}'